# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "inventory-app"
client_id = "012f3a003d78cbdefbc7d9d0da5a12ef"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "fxhiii.myshopify.com"
